# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('organizer', models.CharField(max_length=256)),
                ('website', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('start_time', models.CharField(max_length=256)),
                ('end_time', models.CharField(max_length=256)),
                ('cost', models.CharField(max_length=256)),
                ('venue_name', models.CharField(max_length=256)),
                ('venue_street_address', models.CharField(max_length=256)),
                ('venue_city', models.CharField(max_length=256)),
                ('venue_state', models.CharField(max_length=256)),
                ('venue_zipcode', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMessageLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_received', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingMessageLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='outgoingmessagelog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Person'),
        ),
        migrations.AddField(
            model_name='incomingmessagelog',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Person'),
        ),
    ]
