# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_state',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_street_address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_zipcode',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
