# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20160314_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessagelog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Event'),
        ),
        migrations.AddField(
            model_name='outgoingmessagelog',
            name='type',
            field=models.IntegerField(choices=[(0, b'Which Category'), (1, b'Your Location'), (2, b'Interested In This Event'), (3, b'Event Info'), (4, b'Event Location'), (5, b'Event Time')], default=0),
        ),
    ]
