# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20160413_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingmessagelog',
            name='type',
            field=models.IntegerField(choices=[(0, b'Which Category'), (1, b'Your Location'), (2, b'Interested In This Event'), (3, b'Event Info'), (4, b'Event Location'), (5, b'Event Time'), (6, b'Event Website')], default=0),
        ),
    ]
