# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20160413_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_street_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_zipcode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
